Se trata de un problema real con conocimiento personal, requiere desp…
albertolj/Proyecto-Horario-Enfermera pull request #1
Opened 2023-09-22 08:00 UTC by albertolj

* [ x] ¿Se trata de un problema real del que se tenga conocimiento personal?
* [ x] ¿Se trata de un problema que para solucionar requiera el despliegue
   de una aplicación en la nube?
* [ x] ¿La solución requiere una cierta cantidad de lógica de negocio, en vez
    solucionarse sólo almacenando y buscando?
* [x] ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el
`README`?
* [x] ¿Tienes todos los datos necesarios para poder resolver el problema, o vas
a requerir que el usuario los introduzca?
* [x] ¿Has seguido la lista de comprobación o estás marcando al buen tuntún
todo?

2023-09-23 07:35 UTC, JJ commented
La lista de comprobación requiere un poco de explicación, sobre todo en estos primeros objetivos.

2023-09-23 07:36 UTC, JJ commented
>     * [x]  ¿Has seguido la lista de comprobación o estás marcando al buen tuntún
>       todo?

¿Has mirado lo que has marcado aquí? En general, cuando veo esto marcado dejo de corregir. Haz realmente la lista de comprobación, también revisa el problema sugerido, por favor.

2023-09-28 06:50 UTC, albertolj commented
* [ ] ¿Se trata de un problema real del que se tenga conocimiento personal?
Se tiene conocimiento personal, ya que conozco personas con este problema a la hora de coordinar horarios ya sea para no tener un exceso de trabajo o intentar dejar dias libre para poder irse de vacaciones.
* [ ] ¿Se trata de un problema que para solucionar requiera el despliegue
   de una aplicación en la nube?
Si, ya que la idea es que varias enfermeras puedan intercambiar horarios de forma cómoda, y con una aplicación web o móvil sería más sencillo.
* [ ] ¿La solución requiere una cierta cantidad de lógica de negocio, en vez
    solucionarse sólo almacenando y buscando?
Si, ya que se para poder intercambiar horarios es necesario seguir una serie de restricciones, por lo que no se debería poder intercambiar cualquier horario.
* [ ] ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el
`README`?
Si, creo que todo esta bien.
* [ ] ¿Tienes todos los datos necesarios para poder resolver el problema, o vas
a requerir que el usuario los introduzca?
DIspongo de los datos iniciales, los enfermeros tienen 2 dias de mañanas, 2 dias de tardes y 1 noche y descanso, solo sería necesario saber en que dia de la semana comienza el primer dia de mañana.
* [ ] ¿Has seguido la lista de comprobación o estás marcando al buen tuntún
todo?

2023-09-28 06:51 UTC, albertolj commented
Listo para revisión.

2023-09-28 10:01 UTC, JJ commented
> * [x]  ¿Se trata de un problema real del que se tenga conocimiento personal?
>       Se tiene conocimiento personal, ya que conozco personas con este problema a la hora de coordinar horarios ya sea para no tener un exceso de trabajo o intentar dejar dias libre para poder irse de vacaciones.
> 
>     * [x]  ¿Se trata de un problema que para solucionar requiera el despliegue
>       de una aplicación en la nube?
>       Si, ya que la idea es que varias enfermeras puedan intercambiar horarios de forma cómoda, y con una aplicación web o móvil sería más sencillo.
> 
>     * [x]  ¿La solución requiere una cierta cantidad de lógica de negocio, en vez
>       solucionarse sólo almacenando y buscando?
>       Si, ya que se para poder intercambiar horarios es necesario seguir una serie de restricciones, por lo que no se debería poder intercambiar cualquier horario.
> 
>     * [x]  ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el
>       `README`?
>       Si, creo que todo esta bien.
> 
>     * [x]  ¿Tienes todos los datos necesarios para poder resolver el problema, o vas
>       a requerir que el usuario los introduzca?
>       DIspongo de los datos iniciales, los enfermeros tienen 2 dias de mañanas, 2 dias de tardes y 1 noche y descanso, solo sería necesario saber en que dia de la semana comienza el primer dia de mañana.
> 
>     * [ ]  ¿Has seguido la lista de comprobación o estás marcando al buen tuntún
>       todo?

Esto tiene que ir *solo* en el cuerpo.

2023-09-28 10:04 UTC, JJ requested changes
Trata de expresar claramente el problema, que en este caso sería lo que se está tratando de resolver intercambiando horas. O, en otro caso, tratar de ver el problema más amplio: organizar los turnos de enfermería en algún caso específico (no va a ser lo mismo en urgencias que en paritorio que en atención primaria).
En todo caso, os insisto que tengáis conocimiento personal simplemente porque es esencial para entender realmente cuales son los problemas y qué es lo que busca el cliente en cada caso. ES también la metodología correcta de "empatizar" siguiendo *design thinking*

2023-09-28 10:04 UTC, JJ commented on README.md
> +En este proyecto se intenta solucionar un problemática que ocurre dia a dia, que son los horarios de las enfermeras cuando comienzan a realizar intercambios de horas, por ello se va diseñar una aplic
Por favor, trata de explicar claramente el problema que hay que resolver, sobre todo en un contexto un poco más amplio, y buscando que se pueda resolver en el marco de esta asignatura. Con las enfermeras el único problema no es intercambiar horas de trabajo, sino el horario en sí, que tiene una serie de restricciones; tampoco está claro que "intercambiar" sea un problema, sino más bien algo que quieren hacer para algo, no está claro qué.

2023-09-29 07:38 UTC, albertolj commented
Listo para revisión.

2023-09-29 07:51 UTC, JJ approved these changes
👍

2023-09-29 07:56 UTC, merged

2023-10-11 09:34 UTC, JJ commented
Deberías haber entregado ya el objetivo siguiente; conviene que no dejéis pasar mucho tiempo entre conseguir un objetivo y pasar al siguiente porque al final puede costar trabajo encontrar el tiempo para llevar a cabo los objetivos más complicados.

2023-10-13 10:54 UTC, albertolj commented
Buenas,

Muchas gracias por escribirme, lo agradezco de verdad, aunque ahora 
mismo estoy con mi TFG para intentar entregarlo en noviembre. Intentaré 
conseguir los logros de la asignatura para la extraordinaria.

Un saludo.

El 2023-10-11 11:34, Juan Julián Merelo Guervós escribió:
> Deberías haber entregado ya el objetivo siguiente; conviene que no 
> dejéis pasar mucho tiempo entre conseguir un objetivo y pasar al 
> siguiente porque al final puede costar trabajo encontrar el tiempo para 
> llevar a cabo los objetivos más complicados.

2023-10-24 09:54 UTC, Gdakgdak22 approved these changes

2023-10-24 10:11 UTC, JJ commented
Sólo recordarte que los plazos que ponemos son para los *aprobados en las dos convocatorias*. Es decir, incluso para la entrega del objetivo 1 convendría que los respetaras, porque cuando acabe la lectura puede ser un poco tarde; como dice en [los plazos de entrega del objetivo](http://jj.github.io/IV/documentos/proyecto/1.Infraestructura#plazo-de-entrega), el plazo máximo son 8 semanas, Ten en cuenta que el objetivo 2 se puede tardar unas 4 semanas, sólo para él.